-- ============================================================================
-- Subscription Tracker, Module 2: categories
--
-- WHAT THIS FILE IS
--   A "migration". Your Module 1 schema.sql CREATED tables in an empty
--   project. This file CHANGES tables that already exist and already hold
--   data. That is a different job, and it has to be done in a careful order,
--   which is why the file is longer than the two-table diagram suggests.
--
-- HOW TO RUN IT
--   1. Supabase dashboard -> SQL Editor -> "New query"
--   2. Paste this whole file in
--   3. Click "Run"
--   It is wrapped in a transaction: if any single step fails, the whole thing
--   is rolled back and your database is left exactly as it was. There is no
--   half-applied state to clean up.
--
-- ****************************************************************************
-- READ THIS BEFORE YOU RUN IT
--
--   This migration WILL BREAK the "Add subscription" button in index.html.
--
--   You approved category_id as required and auto_renew as required with no
--   default value. That means the database will now reject any new
--   subscription that does not supply both. index.html does not know these
--   columns exist yet, so every save will fail with a "null value violates
--   not-null constraint" error until the app is updated.
--
--   Reading and viewing existing subscriptions keeps working fine. Only
--   adding and editing breaks.
--
--   This is the correct consequence of your decisions, not a mistake. But you
--   should either run this on a copy of the project, or be ready to do the app
--   wiring right after. Section 7 at the bottom is a one-click undo.
-- ****************************************************************************
--
-- Every line marked "ASSUMPTION" or "NEEDS REVIEW" is a choice I made that
-- you have not approved. They are labelled so you can find and change them.
-- ============================================================================

begin;


-- ----------------------------------------------------------------------------
-- 1. THE CATEGORIES TABLE
--
-- Two columns, exactly as approved. No household_id, no timestamps.
-- ----------------------------------------------------------------------------

create table public.categories (
  -- ASSUMPTION A1 (approved): uuid primary key, generated by the database.
  -- Same choice as every other table in this project, so it stays consistent.
  id    uuid primary key default gen_random_uuid(),

  -- Approved: plain text, required, and deliberately NOT unique.
  name  text not null
);


-- ----------------------------------------------------------------------------
-- 2. SECURITY ON THE NEW TABLE
--
-- NEEDS REVIEW. This is the one decision in this file I could not avoid
-- making, because leaving it out would be a security hole rather than a
-- deferred choice.
--
-- Any table in the public schema WITHOUT row level security is readable by
-- anyone who has your project URL. So categories needs it turned on.
--
-- But "who can see which categories?" has two possible answers, and the
-- approved two-column design does not answer it:
--
--   (a) ONE SHARED LIST for everybody. Categories are just labels, so all
--       users read the same Entertainment / Productivity / Utilities. Nobody
--       can add or rename them from the browser; you edit them here in the
--       SQL Editor. This is what I implemented, because it needs no third
--       column and no third table.
--
--   (b) ONE LIST PER HOUSEHOLD. Each user invents their own categories and
--       manages them in the app. This requires adding household_id to
--       categories, which goes beyond the two-column design you approved.
--
-- I chose (a) to stay inside the approved shape. If you want users to create
-- their own categories, say so and we revisit the table.
-- ----------------------------------------------------------------------------

alter table public.categories enable row level security;

-- Signed-in users can read the category list.
create policy "categories: read all"
  on public.categories for select
  to authenticated
  using (true);

-- Deliberately no insert, update, or delete policy. The category list is
-- managed here in the SQL Editor, not from the browser.


-- ----------------------------------------------------------------------------
-- 3. STARTING CATEGORIES
--
-- Because you chose NOT to make name unique, running this file twice would
-- create a second "Entertainment". The "where not exists" guard below prevents
-- that, so the file is safe to re-run.
--
-- ASSUMPTION A13: the fourth row, "Uncategorized". You did not ask for it, but
-- it is load-bearing. category_id is required, and your existing
-- subscriptions do not have one yet. Every existing row needs to point
-- somewhere valid before the database will accept the "required" rule, so
-- something has to be the temporary home. You can rename or reassign away from
-- it afterwards.
-- ----------------------------------------------------------------------------

insert into public.categories (name)
select v.name
from (values ('Entertainment'), ('Productivity'), ('Utilities'), ('Uncategorized')) as v(name)
where not exists (
  select 1 from public.categories c where c.name = v.name
);


-- ----------------------------------------------------------------------------
-- 4. THE LINK: category_id ON SUBSCRIPTIONS
--
-- This happens in three steps, and the order matters. You cannot declare a
-- column "required" while existing rows have it empty; the database checks
-- every row the moment you make the rule and rejects the whole change. So:
-- add it empty, fill it in, then lock the rule down.
-- ----------------------------------------------------------------------------

-- 4a. Add the column, nullable for now.
--
-- NEEDS REVIEW: you asked me not to decide the update and delete behavior yet.
-- I have therefore written no "on delete" clause at all, which means Postgres
-- uses its built-in default, NO ACTION: it will simply refuse to delete a
-- category while any subscription still points at it. That is a safe
-- placeholder, not a decision. When you configure the relationship properly,
-- the realistic options are:
--   - restrict / no action : block the delete (what you have now)
--   - cascade              : delete the category's subscriptions along with it
-- "set null" is NOT available, because you made category_id required.
alter table public.subscriptions
  add column category_id uuid references public.categories(id);

-- 4b. Point every existing subscription at "Uncategorized".
update public.subscriptions
set category_id = (select id from public.categories where name = 'Uncategorized' limit 1)
where category_id is null;

-- 4c. Now make it required, as approved.
alter table public.subscriptions
  alter column category_id set not null;

-- An index on the column the app will group and filter by. The existing
-- schema.sql does the same for household_id, for the same reason: without it,
-- "show me everything in Entertainment" reads the whole table. Not a field and
-- not a table, so it does not change the approved two-table shape.
create index subscriptions_category_id_idx on public.subscriptions (category_id);


-- ----------------------------------------------------------------------------
-- 5. THE NEW BOOLEAN: auto_renew
--
-- Same three-step dance, for the same reason. You removed the default value,
-- so there is no value the database can invent for rows that already exist.
-- ----------------------------------------------------------------------------

-- 5a. Add it empty.
alter table public.subscriptions
  add column auto_renew boolean;

-- 5b. ASSUMPTION A12, NEEDS REVIEW: fill existing rows with true.
--
-- Removing the default settles what happens to FUTURE rows: the app must
-- always ask. It does not settle what to do with the rows already in your
-- table, which have no answer recorded. I chose true because most consumer
-- subscriptions do auto-renew, so it is right more often than false and
-- errs toward "expect the charge". Change true to false here if you would
-- rather assume the cautious direction, or audit the rows by hand afterwards.
update public.subscriptions
set auto_renew = true
where auto_renew is null;

-- 5c. Required, with no default, as approved. From here on the app must send
-- an explicit true or false on every insert.
alter table public.subscriptions
  alter column auto_renew set not null;


commit;


-- ============================================================================
-- 6. WHAT THIS FILE DELIBERATELY DOES NOT DO
--
-- Three fields in the approved model already exist in your Module 1 database
-- under different names or definitions. I have NOT renamed or altered them,
-- because index.html reads and writes them by their current names and a rename
-- would break the app in a second, separate way:
--
--   approved name       actual column in your database    my recommendation
--   -----------------   ------------------------------    -----------------
--   billing_frequency   billing_period                    rename during app wiring
--   usage_rating        rating                            rename during app wiring
--   cost numeric        cost numeric(10,2)                keep numeric(10,2)
--
-- On cost specifically: your existing column is numeric(10,2), which is
-- stricter than the plain numeric you approved. Loosening it would let values
-- like 9.999 into the table and would contradict the MAX_COST ceiling that
-- index.html already enforces. Staying stricter costs you nothing here, so I
-- left it alone rather than widening it. Tell me if you want it widened.
--
-- Also worth correcting: is_active is NOT new in Module 2. It already exists
-- in your Module 1 schema.sql as "boolean not null default true". I described
-- it as a new field earlier in our conversation and that was wrong. auto_renew
-- is the only genuinely new Boolean in this module.
--
--
-- 7. UNDO
--
-- If you want to reverse everything above, run this block on its own. It
-- returns the database to its exact pre-migration state.
--
--   begin;
--     drop index if exists public.subscriptions_category_id_idx;
--     alter table public.subscriptions drop column if exists category_id;
--     alter table public.subscriptions drop column if exists auto_renew;
--     drop policy if exists "categories: read all" on public.categories;
--     drop table if exists public.categories;
--   commit;
--
-- ============================================================================
